### ISSUE TITLE
75 view range version for CE players

### ISSUE THREAD

**Issue by i2iddik** [lukakama/rimworld-mod-real-fow#12]
I have made a 75 veiw range version of this mod for CE players but cannot work out how to add it as a "fork" on github.
would it be possible if you could set the view range of the pawns (mech and non mech) in the mod options

**Comment by luca-de-petrillo-website** [comment]
The base view range can now be customized by patching the Mod_Defaults.xml file using a "mod xml patch extension" (like it is already done by the "Real Fog of War Extended" mod to extends other mod's features).

**Comment by lukakama** [comment]
The base view range can now be customized by patching the Mod_Defaults.xml file using a "mod xml patch extension" (like it is already done by the "Real Fog of War Extended" mod to extends other mod's features).
